### ISSUE TITLE
Cannot read hdfeos5 field

### ISSUE THREAD

**Issue by quintusdias** [quintusdias/pyhdfeos#67]
```
python3 zoo/gesdisc/omi/OMI_OMCLDO2G.py
Traceback (most recent call last):
  File "zoo/gesdisc/omi/OMI_OMCLDO2G.py", line 147, in <module>
    run(hdffile)
  File "zoo/gesdisc/omi/OMI_OMCLDO2G.py", line 41, in run
    data = grid[DATAFIELD_NAME][0, :, :]
  File "/home/jevans/.local/lib/python3.4/site-packages/pyhdfeos-0.1.1-py3.4-linux-x86_64.egg/pyhdfeos/grids.py", line 491, in __getitem__
    rows_start = 0 if rows.start is None else rows.start
AttributeError: 'str' object has no attribute 'start'
```

File is OMI-Aura_L2G-OMCLDO2G_2007m0129_v002-2007m0130t174603.he5

**Comment by quintusdias** [comment]
not a bug, example was incorrectly coded
