### ISSUE TITLE
eosdump fails on TES-Aura_L3-CH4_r0000010410_F01_07.he5

### ISSUE THREAD

**Issue by quintusdias** [quintusdias/pyhdfeos#8]
```
Traceback (most recent call last):
  File "/home/jevans/.local/bin/eosdump", line 9, in <module>
    load_entry_point('pyhdfeos==0.1.0rc1', 'console_scripts', 'eosdump')()
  File "/home/jevans/.local/lib/python3.4/site-packages/pyhdfeos-0.1.0rc1-py3.4-linux-x86_64.egg/pyhdfeos/command_line.py", line 13, in dump_metadata
    gdf = GridFile(args.filename)
  File "/home/jevans/.local/lib/python3.4/site-packages/pyhdfeos-0.1.0rc1-py3.4-linux-x86_64.egg/pyhdfeos/grids.py", line 295, in __init__
    self.grids[gridname] = _Grid(self.gdfid, gridname, self._he)
  File "/home/jevans/.local/lib/python3.4/site-packages/pyhdfeos-0.1.0rc1-py3.4-linux-x86_64.egg/pyhdfeos/grids.py", line 73, in __init__
    self.attrs[attr] = self._he.gdreadattr(self.gridid, attr)
AttributeError: 'module' object has no attribute 'gdreadattr'
```

**Comment by quintusdias** [comment]
`gdreadattr` not implemented for hdfeos5 module
