### ISSUE TITLE
eosdump fails on SW_S3E_2003100.20053531923.hdf

### ISSUE THREAD

**Issue by quintusdias** [quintusdias/pyhdfeos#9]
```
Traceback (most recent call last):
  File "/home/jevans/.local/bin/eosdump", line 9, in <module>
    load_entry_point('pyhdfeos==0.1.0rc1', 'console_scripts', 'eosdump')()
  File "/home/jevans/.local/lib/python3.4/site-packages/pyhdfeos-0.1.0rc1-py3.4-linux-x86_64.egg/pyhdfeos/command_line.py", line 13, in dump_metadata
    gdf = GridFile(args.filename)
  File "/home/jevans/.local/lib/python3.4/site-packages/pyhdfeos-0.1.0rc1-py3.4-linux-x86_64.egg/pyhdfeos/grids.py", line 295, in __init__
    self.grids[gridname] = _Grid(self.gdfid, gridname, self._he)
  File "/home/jevans/.local/lib/python3.4/site-packages/pyhdfeos-0.1.0rc1-py3.4-linux-x86_64.egg/pyhdfeos/grids.py", line 47, in __init__
    dimnames, dimlens = self._he.gdinqdims(self.gridid)
  File "/home/jevans/.local/lib/python3.4/site-packages/pyhdfeos-0.1.0rc1-py3.4-linux-x86_64.egg/pyhdfeos/lib/he4.py", line 408, in gdinqdims
    dimlens = np.zeros(ndims, dtype=np.int32)
ValueError: negative dimensions are not allowed
Exception ignored in: <bound method _Grid.__del__ of <pyhdfeos.grids._Grid object at 0x7fae61088390>>
Traceback (most recent call last):
  File "/home/jevans/.local/lib/python3.4/site-packages/pyhdfeos-0.1.0rc1-py3.4-linux-x86_64.egg/pyhdfeos/grids.py", line 76, in __del__
    self._he.gddetach(self.gridid)
  File "/home/jevans/.local/lib/python3.4/site-packages/pyhdfeos-0.1.0rc1-py3.4-linux-x86_64.egg/pyhdfeos/lib/he4.py", line 181, in gddetach
    _handle_error(status)
  File "/home/jevans/.local/lib/python3.4/site-packages/pyhdfeos-0.1.0rc1-py3.4-linux-x86_64.egg/pyhdfeos/lib/he4.py", line 65, in _handle_error
    raise IOError("Library routine failed.")
OSError: Library routine failed.
```

**Comment by quintusdias** [comment]
duplicate of #15
